import { escapeHtml } from './escapeHtml';
import type { Attempt } from '../api/attempts';

export function buildAttemptPdfHtml(attempt: Attempt): string {
  const exam = attempt.exam ?? null;
  const school = attempt.school ?? null;
  const answers = attempt.answers?.attempts ?? [];

  const answerRows = answers
    .map((item: any) => {
      let value = item.attempt;
      let rendered: string;
      if (value === null || value === undefined) {
        rendered = '<em>(no answer)</em>';
      } else if (typeof value === 'object') {
        rendered = escapeHtml(JSON.stringify(value, null, 2));
      } else {
        rendered = escapeHtml(String(value));
      }
      return `<tr>
        <td style="padding:8px;border:1px solid #d1d5db;">${escapeHtml(String(item.question_id))}</td>
        <td style="padding:8px;border:1px solid #d1d5db;white-space:pre-wrap;">${rendered}</td>
      </tr>`;
    })
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <title>Attempt Report</title>
</head>
<body style="font-family:-apple-system,'Segoe UI',Arial,sans-serif;color:#111827;margin:0;padding:32px;">
  <div style="border-bottom:3px solid ${escapeHtml(school?.primary_color || '#2563eb')};padding-bottom:16px;margin-bottom:24px;">
    ${school?.name ? `<h1 style="font-size:22px;margin:0;">${escapeHtml(school.name)}</h1>` : ''}
    <h1 style="font-size:26px;margin:8px 0 0;">Smart Exam Taker - Attempt Report</h1>
  </div>

  <h2 style="font-size:18px;margin-top:24px;">Exam</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Title</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(exam?.title || 'Unknown exam')}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Code</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(exam?.code || '')}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Status</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(attempt.status)}</td></tr>
  </table>

  <h2 style="font-size:18px;margin-top:24px;">Student</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Name</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(attempt.student_first_name)} ${escapeHtml(attempt.student_last_name)}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Student ID</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(attempt.student_id_number)}</td></tr>
    ${attempt.department ? `<tr><td style="padding:6px;border:1px solid #d1d5db;">Department</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(attempt.department)}</td></tr>` : ''}
    ${attempt.section ? `<tr><td style="padding:6px;border:1px solid #d1d5db;">Section</td><td style="padding:6px;border:1px solid #d1d5db;">${escapeHtml(attempt.section)}</td></tr>` : ''}
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Started</td><td style="padding:6px;border:1px solid #d1d5db;">${new Date(attempt.started_at).toLocaleString()}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Submitted</td><td style="padding:6px;border:1px solid #d1d5db;">${attempt.submitted_at ? new Date(attempt.submitted_at).toLocaleString() : 'Not submitted'}</td></tr>
  </table>

  <h2 style="font-size:18px;margin-top:24px;">Score</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <tr><td style="padding:6px;border:1px solid #d1d5db;">Objective</td><td style="padding:6px;border:1px solid #d1d5db;">${attempt.objective_score ?? '-'}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;">AI Score</td><td style="padding:6px;border:1px solid #d1d5db;">${attempt.ai_score ?? '-'}</td></tr>
    <tr><td style="padding:6px;border:1px solid #d1d5db;font-weight:700;">Total</td><td style="padding:6px;border:1px solid #d1d5db;font-weight:700;">${attempt.total_score ?? '-'}</td></tr>
  </table>

  <h2 style="font-size:18px;margin-top:24px;">Answers</h2>
  <table style="width:100%;border-collapse:collapse;font-size:14px;">
    <thead>
      <tr>
        <th style="text-align:left;padding:8px;border:1px solid #d1d5db;">Question ID</th>
        <th style="text-align:left;padding:8px;border:1px solid #d1d5db;">Answer</th>
      </tr>
    </thead>
    <tbody>${answerRows}</tbody>
  </table>

  <p style="margin-top:32px;font-size:12px;color:#6b7280;">
    Generated by Smart Exam Taker on ${new Date().toLocaleString()}
  </p>
</body>
</html>`;
}